### ISSUE TITLE
Integrate Codeforces API with user

### ISSUE THREAD

**Issue by Shubhrajyoti-Dey-FrosTiK** [Shubhrajyoti-Dey-FrosTiK/college-community-backend#11]

**Comment by Abhyuday03** [comment]
I can work on this. Please assign it to me

**Comment by Shubhrajyoti-Dey-FrosTiK** [comment]
Yes sure.
I have made the initial PR to this issue. You can work on that to integrate with the User Schema.

But to be honest I am not sure this will be counted as a valid Hactoberfest PR. I will accept your PR if I find it valid and will attach the Hacktoberfest labels on it. But cant assure this will be counted or not.
